allowBuilds:
  esbuild: true
  "@parcel/watcher": true
  unrs-resolver: true
  vue-demi: false
  sharp: true
packages:
  - playground
  - packages/*
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@michaelthielemann/*'
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 129600
trustPolicyExclude:
  - '@michaelthielemann/*'
blockExoticSubdeps: true
