import type { TriggerConfig } from "@michaelthielemann/kestrel/defineConfig";
import type { Feature } from "./index";

export interface TriggerEntry {
  trigger: TriggerConfig;
  feature?: Feature;
}

export const canonicalTriggers: readonly TriggerEntry[] = [
  { trigger: { http: "POST /login", pipeline: "login" } },
  { trigger: { http: "POST /logout", pipeline: "logout" } },
  { trigger: { http: "GET /me", pipeline: "me" } },
  { trigger: { http: "POST /me/password", pipeline: "changePassword" } },
  { trigger: { http: "GET /users", pipeline: "listUsers" } },
  { trigger: { http: "POST /users", pipeline: "createUser" } },
  { trigger: { http: "GET /users/:id", pipeline: "getUser" } },
  { trigger: { http: "PUT /users/:id/password", pipeline: "setPassword" } },
  { trigger: { http: "DELETE /users/:id", pipeline: "deactivateUser" } },
  { trigger: { http: "POST /users/:id/activate", pipeline: "activateUser" } },
  { trigger: { http: "GET /admin/publish-status/pages/:id", pipeline: "pagePublishStatus" }, feature: "delivery" },
  { trigger: { http: "POST /admin/publish-all/pages", pipeline: "publishAllPages" }, feature: "delivery" },
  { trigger: { http: "GET /admin/references/broken", pipeline: "brokenReferences" }, feature: "references" },
  { trigger: { http: "GET /admin/references/to/pages", pipeline: "pageReferrersMany" }, feature: "references" },
  { trigger: { http: "GET /admin/references/to/pages/:id", pipeline: "pageReferrers" }, feature: "references" },
  { trigger: { http: "GET /admin/references/to/media", pipeline: "mediaReferrersMany" }, feature: "references" },
  { trigger: { http: "GET /admin/references/to/media/:id", pipeline: "mediaReferrers" }, feature: "references" },
  { trigger: { http: "POST /admin/references/rebuild", pipeline: "rebuildReferences" }, feature: "references" },
  { trigger: { http: "GET /admin/links/broken", pipeline: "brokenLinks" }, feature: "links" },
  { trigger: { http: "POST /admin/links/rebuild", pipeline: "rebuildLinks" }, feature: "links" },
  { trigger: { http: "GET /settings", pipeline: "getSettings" } },
  { trigger: { http: "PUT /settings", pipeline: "setSettings" } },
  { trigger: { http: "GET /redirects", pipeline: "getRedirects" }, feature: "redirects" },
  { trigger: { http: "PUT /redirects", pipeline: "setRedirects" }, feature: "redirects" },
  { trigger: { http: "GET /redirects.json", pipeline: "renderRedirects" }, feature: "redirects" },
  { trigger: { http: "GET /site/*path", pipeline: "resolvePage" } },
  { trigger: { http: "POST /media", pipeline: "uploadMedia" } },
  { trigger: { http: "POST /admin/media/export", pipeline: "exportMedia" } },
  { trigger: { http: "POST /admin/media/reconcile", pipeline: "reconcileMediaReport" } },
  { trigger: { http: "POST /admin/media/reconcile/delete", pipeline: "reconcileMediaDelete" } },
  { trigger: { http: "GET /media/folders", pipeline: "listMediaFolders" } },
  { trigger: { http: "POST /media/folders", pipeline: "createMediaFolder" } },
  { trigger: { http: "PATCH /media/folders/*path", pipeline: "renameMediaFolder" } },
  { trigger: { http: "DELETE /media/folders/*path", pipeline: "deleteMediaFolder" } },
  { trigger: { http: "GET /media", pipeline: "listMedia" } },
  { trigger: { http: "GET /media/:id", pipeline: "getMedia" } },
  { trigger: { http: "GET /media/:id/file", pipeline: "downloadMedia" } },
  { trigger: { http: "GET /media/:id/variants/:file", pipeline: "serveImageVariant" }, feature: "images" },
  { trigger: { http: "PATCH /media/:id", pipeline: "updateMedia" } },
  { trigger: { http: "DELETE /media/:id", pipeline: "deleteMedia" } },
  { trigger: { http: "PUT /admin/images/sizes", pipeline: "registerImageSizes" }, feature: "images" },
  { trigger: { http: "GET /admin/images/sizes", pipeline: "listImageSizes" }, feature: "images" },
  { trigger: { http: "POST /admin/images/sync", pipeline: "syncImages" }, feature: "images" },
  { trigger: { http: "POST /admin/images/prune", pipeline: "pruneImages" }, feature: "images" },
  { trigger: { http: "GET /admin/images/status", pipeline: "imagesStatus" }, feature: "images" },
  { trigger: { http: "GET /admin/replication/status", pipeline: "replicationStatus" }, feature: "replication" },
  { trigger: { http: "GET /admin/replication/points", pipeline: "replicationPoints" }, feature: "replication" },
  { trigger: { http: "POST /admin/replication/snapshot", pipeline: "replicationSnapshot" }, feature: "replication" },
  { trigger: { http: "POST /admin/replication/restore", pipeline: "replicationRestore" }, feature: "replication" },
  { trigger: { http: "GET /admin/migrations", pipeline: "listMigrations" }, feature: "migrations" },
  { trigger: { http: "POST /admin/migrations/apply", pipeline: "applyMigrations" }, feature: "migrations" },
  { trigger: { cron: "30 2 * * *", pipeline: "scanReferences" }, feature: "references" },
  { trigger: { cron: "0 3 * * *", pipeline: "checkLinks" }, feature: "links" },
  { trigger: { cron: "0 * * * *", pipeline: "cleanupSessions" } },
  { trigger: { cron: "*/5 * * * *", pipeline: "sweepRateLimits" }, feature: "ratelimit" },
  { trigger: { cron: "*/5 * * * *", pipeline: "resumeImages" }, feature: "images" },
  { trigger: { cron: "30 3 * * *", pipeline: "reconcileMedia" } },
  { trigger: { cron: "* * * * *", pipeline: "replicate" }, feature: "replication" },
  { trigger: { event: "media.uploaded", pipeline: "generateImageVariants" }, feature: "images" },
  { trigger: { event: "auth.loggedIn", pipeline: "auditAuth" }, feature: "audit" },
  { trigger: { event: "auth.loggedOut", pipeline: "auditAuth" }, feature: "audit" },
];
