import type { SerializedBlock, SerializedField } from "./app/types/kestrel";
import type { FieldTypes } from "./field-types";

type Schema = Record<string, unknown>;

const NODE_REF = { $ref: "#/$defs/node" };

function fieldSchema(field: SerializedField, fieldTypes: FieldTypes): Schema {
  const nullable = (schema: Schema): Schema => (field.required ? schema : { anyOf: [schema, { type: "null" }] });
  switch (field.type) {
    case "richtext":
      return nullable({ type: "string", format: "html" });
    case "text":
    case "media":
    case "relation":
      return nullable({ type: "string" });
    case "slug":
      return nullable({ type: "string", pattern: "^[a-z0-9]+(-[a-z0-9]+)*$" });
    case "number":
    case "datetime":
      return nullable({ type: "number" });
    case "boolean":
      return nullable({ type: "boolean" });
    case "choice": {
      const choices = (field.options?.choices as { value: string }[] | undefined) ?? [];
      const values = { type: "string", enum: choices.map((c) => c.value) };
      return field.options?.multiple ? nullable({ type: "array", items: values }) : nullable(values);
    }
    case "link":
      return nullable({
        type: "object",
        properties: { type: { type: "string", enum: ["internal", "external", "email", "tel"] }, label: { type: "string" } },
        required: ["type"],
      });
    case "repeater": {
      const fields = (field.options?.fields as Record<string, SerializedField> | undefined) ?? {};
      return nullable({ type: "array", items: propsSchema(fields, fieldTypes) });
    }
    default: {
      const custom = fieldTypes[field.type];
      return custom === undefined ? {} : nullable({ ...custom.schema });
    }
  }
}

function propsSchema(fields: Record<string, SerializedField>, fieldTypes: FieldTypes): Schema {
  const properties: Record<string, Schema> = {};
  const required: string[] = [];
  for (const [name, field] of Object.entries(fields)) {
    properties[name] = fieldSchema(field, fieldTypes);
    if (field.required) required.push(name);
  }
  return { type: "object", properties, ...(required.length ? { required } : {}), additionalProperties: false };
}

function blockNodeSchema(block: SerializedBlock, fieldTypes: FieldTypes): Schema {
  const slots: Record<string, Schema> = {};
  for (const slot of block.slots ?? []) slots[slot] = { type: "array", items: NODE_REF };
  return {
    type: "object",
    properties: {
      id: { type: "string" },
      type: { const: block.name },
      props: propsSchema(block.fields, fieldTypes),
      slots: { type: "object", properties: slots, additionalProperties: false },
    },
    required: ["type"],
    additionalProperties: false,
  };
}

export function blockSchema(blocks: readonly SerializedBlock[], fieldTypes: FieldTypes = {}): Schema {
  const $defs: Record<string, Schema> = { node: { oneOf: blocks.map((b) => ({ $ref: `#/$defs/${b.name}` })) } };
  for (const block of blocks) $defs[block.name] = blockNodeSchema(block, fieldTypes);
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $comment: "Generated by kestrel-web from app/blocks/*.vue on every build - do not edit",
    $id: "pages.body",
    type: "array",
    items: NODE_REF,
    $defs,
  };
}
